"""Exact, reversible coarsening of labeled directed rooted trees."""

from .coarsener import TreeCoarsener
from .compose import CombinedTreeDecoder, CombinedTreeEncoder, combine
from .contraction import Contraction, RuleBasedEncoder, apply_contraction_batch
from .decoder import TreeDecoder
from .encoder import EncodingRule, TreeEncoder, Vocabulary
from .exceptions import (
    AttachmentError,
    BoundaryExpansionError,
    CompositionError,
    ConfigurationError,
    DecodeSelectionError,
    ExactTypeError,
    FittingSizeError,
    GraphSchemaError,
    InternalInvariantError,
    LabelMetadataError,
    NotFittedError,
    ProvenanceError,
    StageOrderError,
    TargetNotFoundError,
    TreeCoarseningError,
    TreeStructureError,
    TypeOwnershipError,
    ValidationError,
)
from .provenance import GRAPH_ATTRS_KEY, NODE_ATTRS_KEY, PROVENANCE_KEY
from .schema import (
    EDGE_FIELDS,
    FITTING_SIZES_KEY,
    NODE_FIELDS,
    SCHEMA_KEY,
    SCHEMA_VERSION,
    ValidationLevel,
    fit_corpus_fitting_sizes,
    get_graph_fitting_sizes,
    graph_stages,
    normalize_raw_graph,
    prepare_graph,
)
from .stage_decoder import StructuralStageDecoder
from .structural import (
    BaseType,
    CompositeType,
    ExactType,
    MatchingLabel,
    base_type,
    exact_root_count,
    exact_site_count,
    exact_type_label,
    is_base_type,
)
from .validation import validate_encoded_tree, validate_raw_tree
from .coarseners import (
    EdgeBPECoarsener,
    EdgeBPEEncoder,
    EdgeBPERule,
    NamedVertexCoarsener,
    NamedVertexEncoder,
    ParametricStarCoarsener,
    ParametricStarDecoder,
    ParametricStarEncoder,
    count_pair_score,
    edge_bpe_token,
    named_component_label,
    normalized_pair_score,
    parametric_star_label,
    size_weighted_pair_score,
)

__all__ = [
    "AttachmentError",
    "BaseType",
    "BoundaryExpansionError",
    "CombinedTreeDecoder",
    "CombinedTreeEncoder",
    "CompositeType",
    "CompositionError",
    "ConfigurationError",
    "Contraction",
    "DecodeSelectionError",
    "EDGE_FIELDS",
    "EdgeBPECoarsener",
    "EdgeBPEEncoder",
    "EdgeBPERule",
    "EncodingRule",
    "ExactType",
    "ExactTypeError",
    "FITTING_SIZES_KEY",
    "FittingSizeError",
    "GRAPH_ATTRS_KEY",
    "GraphSchemaError",
    "InternalInvariantError",
    "LabelMetadataError",
    "MatchingLabel",
    "NODE_ATTRS_KEY",
    "NODE_FIELDS",
    "NamedVertexCoarsener",
    "NamedVertexEncoder",
    "NotFittedError",
    "PROVENANCE_KEY",
    "ParametricStarCoarsener",
    "ParametricStarDecoder",
    "ParametricStarEncoder",
    "ProvenanceError",
    "RuleBasedEncoder",
    "SCHEMA_KEY",
    "SCHEMA_VERSION",
    "StageOrderError",
    "StructuralStageDecoder",
    "TargetNotFoundError",
    "TreeCoarsener",
    "TreeCoarseningError",
    "TreeDecoder",
    "TreeEncoder",
    "TreeStructureError",
    "TypeOwnershipError",
    "ValidationError",
    "ValidationLevel",
    "Vocabulary",
    "apply_contraction_batch",
    "base_type",
    "combine",
    "count_pair_score",
    "edge_bpe_token",
    "exact_root_count",
    "exact_site_count",
    "exact_type_label",
    "fit_corpus_fitting_sizes",
    "get_graph_fitting_sizes",
    "graph_stages",
    "is_base_type",
    "named_component_label",
    "normalize_raw_graph",
    "normalized_pair_score",
    "parametric_star_label",
    "prepare_graph",
    "size_weighted_pair_score",
    "validate_encoded_tree",
    "validate_raw_tree",
]
